project:
  type: website

website:
  title: "SPI Québec"
  image: assets/img/logo.png

  navbar:
    logo: assets/img/logo.png
    logo-alt: "BdQc logo"
    title: false
    collapse-below: lg
    tools:
      - icon: github
        href: https://github.com/Sckende/QUARTO_WEB_SPI
        text: SPI GitHub
    left:
      - text: "Home"
        file: index.qmd
      - text: "Histoire de biodiversité"
        file: hist_biodiv.qmd
      - text: "Indice de Protection des Espèces"
        file: indic_protec_esp.qmd
      - text: "À propos"
        file: about.qmd
  sidebar:
    - title: "Home"
      style: docked #floating
      background: light
      contents:
        - index.qmd

    - title: "Histoire de biodiversité"
      contents:
        - hist_biodiv.qmd

    - title: "Indice de Protection des Espèces"
      contents:
        - indic_protec_esp.qmd
        - section: "Occurrences"
          contents:
            - SPI_occurrences/0_Occurrences_methodo.qmd
            - SPI_occurrences/1_Occurrences_SPI_explo.qmd
            - 2_Occurrences_SPI_visual.qmd

        - section: "Aires de distribution"
          contents:
            - SPI_ranges/0_Ranges_methodo.qmd
            - SPI_ranges/1_Ranges_SPI_explo.qmd
            - 2_Ranges_SPI_visual.qmd

        - section: "SDM - INLA"
          contents:
            - SPI_Bellavance/0_Bellavance_methodo.qmd
            - SPI_Bellavance/1_Bellavance_SPI_explo.qmd
            - SPI_Bellavance/2_Bellavance_SPI_visual.qmd

    - title: "À propos"
      contents:
        - about.qmd
format:
  html:
    theme:
      light: cosmo
      dark: darkly
    css: styles.css
    toc: true
