---
title: "Histoire de biodiversité"
---


```{r}
#| echo: false

# Load data
SPI_OCC <- read.csv("results/SPI_OCC.csv")
SPI_OCC <- SPI_OCC[SPI_OCC$SPECIES != "Information masquée",]
SPI_OCC_2023 <- SPI_OCC[SPI_OCC$YEAR == 2023,]

SPI_RANGES <- read.csv("results/SPI_ranges.csv")
SPI_RANGES <- SPI_RANGES[SPI_RANGES$SPECIES != "Information masquée",]
SPI_RANGES_2023 <- SPI_RANGES[SPI_RANGES$YEAR == 2023,]

```


## Points clefs

### Contexte

Le Québec a annoncé le 31 décembre 2020 avoir atteint son objectif de protection de 17% du territoire ([registre des aires protégées du Québec](https://www.environnement.gouv.qc.ca/biodiversite/aires_protegees/registre/)). Mais la biodiversité est-elle représentée par ces aires protégées ?

Pour explorer cette question, nous avons mesuré la proportion de l'aire de répartition de plusieurs espèces (Amphibiens, Mammifères, Poissons, Reptiles) qui se trouve protégée par des aires protégées inscrites au registre du Québec. Ces aires de répartition informent sur la présence de l'espèce au Québec et la proportion de ces aires qui sont protégées nous informe sur la représentativité de la biodiversité dans les aires protégées.

Nous avons comparé ces résultats à ceux obtenus avec les occurrences du CDPNQ. Ces dernières se concentrent sur les espèces en situation précaire et sont construites à partir d'une ou de plusieurs observations. L'occurrence est définie par une zone tampon établie autour des observations, caractérisant ainsi l'habitat utilisé par une population locale. 

L'intérêt de cette comparaison est de voir si la protection des habitats où la présence d'une espèce est confirmée est comparable à la protection des habitats potentiels de l'espèce (aire de distribution). 

Puisqu'il existe une disparité entre le sud et le nord du Québec dans la superficie protégée du territoire, nous avons aussi mesuré séparément la quantité d'habitat protégé pour le nord et sud, suivant la division définie par le territoire du Plan Nord (49e parallèle).

### Messages clés

- En général, aacélération de la protection des espèces au cours des dernières décennies
- Le territoire nordique du Québec est plus protégé que le territoire sous le 49ème parallèle où se concentre la biodiversité
- Sur le territoire nordique du Québec, les espèces sont mieux protégées que sur le territoire en dessous du 49ème parallèle
- Globalement, la protection des espèces présente une grande variabilité (cf exemples ?)
- Analyse globale de la part de BQ, d'autres équipes, telle que la Division du Rétablissement de la Direction des Espèces Fauniques Menacées et Vulnérables du MELCCFP, produisent des analyses plus précises pour les espèces vulnérables et menacées
- Biodiversité Québec est au centre de la communication et du suivi de la biodiversité du Québec


### Aires protégées du Québec
- [Carte](https://reseaubiodiversitequebec.github.io/SPI_website/indic_protec_esp.html#repr%C3%A9sentation-actuelle-des-aires-prot%C3%A9g%C3%A9es-du-qu%C3%A9bec) de représentation des aires protégées du Québec (la carte n'est pas à jour avec les chiffres qui suivent, toujours en attente de la mise à jour du MELCCFP)
- Au 30 septembre 2023, le réseau d’aires protégées de l’ensemble du Québec s’étend sur 274 374 km2 ou 16,42% du territoire
  - Milieu continental (terrestre et eaux douces) : 255 381 km2 ou 16,89%
  - Milieu marin et côtier : 18 992 km2 ou 12,21%
  - Le territoire du Plan Nord (Au delà du 49e parallèle) est protégé sur 19,17% de sa superficie
- Importante accélération de la protection du territoire depuis le début des années 2000
- Distribution des aires protégées : plus d'aires dans le nord et certaines créations d'aires ont marqué de grandes augmentations dans la couverture du territoire

### Protection des espèces

**Aires de distribution**

Visualisation des résultats dans l'[onglet](https://reseaubiodiversitequebec.github.io/SPI_website/2_Ranges_SPI_visual.html) dédié au projet.

- Augmentation de la protection pour tous les groupes d'espèces
- En moyenne, `r round(mean(SPI_RANGES_2023$SPI, na.rm = T), digit = 2)`% de la superficie des aires de distribution se trouvent dans des aires protégées. C'est en deçà de l'objectif de 17% de protection du territoire.
- Nombre d'espèces protégées à 17% : `r sum(SPI_RANGES_2023$SPI >= 0.17, na.rm = T)` espèces (`r round(sum(SPI_RANGES_2023$SPI >= 0.17, na.rm = T) / nrow(SPI_RANGES_2023) * 100, digit = 2)`%)
- `r sum(SPI_RANGES_2023$SPI_NORTH >= 0.17, na.rm = T)` espèces (`r round(sum(SPI_RANGES_2023$SPI_NORTH >= 0.17, na.rm = T) / nrow(SPI_RANGES_2023) * 100, digit = 2)`%) dans le nord
- `r sum(SPI_RANGES_2023$SPI_SOUTH >= 0.17, na.rm = T)` espèces (`r round(sum(SPI_RANGES_2023$SPI_SOUTH >= 0.17, na.rm = T) / nrow(SPI_RANGES_2023) * 100, digit = 2)`%) dans le sud

**Occurrences**

Visualisation des résultats dans l'[onglet](https://reseaubiodiversitequebec.github.io/SPI_website/2_Occurrences_SPI_visual.html) dédié au projet.

- En moyenne, `r round(mean(SPI_OCC_2023$SPI, na.rm = T), digit = 2)`% de la superficie des occurrences d'une espèce se trouve dans des aires protégées
- Interprétations possibles : 
  - Les aires protégées protègent davantage les habitats utilisés par les espèces en situation précaire
  - Les espèces en situation précaire sont plus souvent observées dans des aires protégées
  - Réalité : un peu des deux
- Nombre d'espèces protégées à 17% : `r sum(SPI_OCC_2023$SPI >= 0.17, na.rm = T)` espèces (`r round(sum(SPI_OCC_2023$SPI >= 0.17, na.rm = T) / nrow(SPI_OCC_2023) * 100, digit = 2)`%)
- `r sum(SPI_OCC_2023$SPI_NORTH >= 0.17, na.rm = T)` espèces (`r round(sum(SPI_OCC_2023$SPI_NORTH >= 0.17, na.rm = T) / nrow(SPI_OCC_2023) * 100, digit = 2)`%) dans le nord
- `r sum(SPI_OCC_2023$SPI_SOUTH >= 0.17, na.rm = T)` espèces (`r round(sum(SPI_OCC_2023$SPI_SOUTH >= 0.17, na.rm = T) / nrow(SPI_OCC_2023) * 100, digit = 2)`%) dans le sud

### Protection des espèces dans le Nord vs. dans le Sud
- La définition du Nord et du Sud utilisée est celle du territoire du Plan Nord (49e parallèle), en conformité avec le registres des aires protégées du Québec (MELCCFP).
- La distribution nordique des espèces est mieux protégée que celle du sud : 
  - `r round(mean(SPI_RANGES_2023$SPI_NORTH, na.rm = T)*100, digit = 2)`% (sd = `r round(sd(SPI_RANGES_2023$SPI_NORTH, na.rm = T)*100, digit = 2)`) de la superfice > 49e parallèle vs. `r round(mean(SPI_RANGES_2023$SPI_SOUTH, na.rm = T)*100, digit = 2)`% (sd = `r round(sd(SPI_RANGES_2023$SPI_SOUTH, na.rm = T)*100, digit = 2)`) sous le 49e parallèle de la superficie des aires de distribution est protégée
  - `r round(mean(SPI_OCC_2023$SPI_NORTH, na.rm = T)*100, digit = 2)`% (sd = `r round(sd(SPI_OCC_2023$SPI_NORTH, na.rm = T)*100, digit = 2)`) de la superfice > 49e parallèle vs. `r round(mean(SPI_OCC_2023$SPI_SOUTH, na.rm = T)*100, digit = 2)`% (sd = `r round(sd(SPI_OCC_2023$SPI_SOUTH, na.rm = T)*100, digit = 2)`) sous le 49e parallèle de la superficie des occurrences est protégée

### Méthodologie

La méthodologie est présentée dans l'[onglet](https://reseaubiodiversitequebec.github.io/SPI_website/indic_protec_esp.html) Indice de Protection des Espèces du site web dédié au projet.

La méthodologie utilisée pour le calcul est basée sur la méthode de l'Indice de Protection des Espèces tel que présenté par [GEO BON](https://geobon.org/ebvs/indicators/species-protection-index/) (SPI). 